import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import FuncFormatter, MaxNLocator

REINSERT_COLOR = "#9AC9DB"
UPDATE_COLOR = "#BB9727"
AMPLIFICATION_COLOR = "#C824A3"

PANEL_FIGSIZE = (16, 6)
GLOBAL_FONT_FAMILY = "Arial"
GLOBAL_FONT_SIZE = 34.0
VALUE_FONT_SIZE = 26.0
AXIS_LINEWIDTH = 1.5
TICK_LINEWIDTH = 1.5
BAR_EDGE_LINEWIDTH = 1.4
LEFT_Y_NBINS = 6
RIGHT_Y_NBINS = 5
LEFT_Y_LABELPAD = 14
RIGHT_Y_LABELPAD = 22
LEFT_Y_TICK_PAD = 2
RIGHT_Y_TICK_PAD = 9
BAR_TOP_PADDING_RATIO = 0.16
LINE_TOP_PADDING_RATIO = 0.32
BAR_LABEL_OFFSET_RATIO = 0.02
LINE_LABEL_OFFSET_RATIO = 0.05
MIN_BAR_LABEL_OFFSET = 0.08
MIN_LINE_LABEL_OFFSET = 0.04
RIGHT_LINE_HEIGHT_FRACTION = 0.62


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot write amplification from TSV generated by run_motivation_exp2b.sh"
    )
    parser.add_argument(
        "--data",
        default="write_amplification.tsv",
        help="Input TSV path with columns: gc_ratio, reinsert_bytes, update_bytes, update_insert_ratio",
    )
    parser.add_argument(
        "--output",
        default="write_amplification.pdf",
        help="Output image filename (png/pdf/svg)",
    )
    parser.add_argument(
        "--x-axis-label",
        default="GC threshold",
        help="X-axis label",
    )
    parser.add_argument(
        "--bar-y-label",
        default="Write volumn (GiB)",
        help="Left y-axis label for bars",
    )
    parser.add_argument(
        "--line-y-label",
        default="Write amplification",
        help="Right y-axis label for line",
    )
    return parser.parse_args()


def read_tsv(data_path: Path):
    if not data_path.exists():
        raise FileNotFoundError(f"Input file not found: {data_path}")

    gc_ratios = []
    reinsert_bytes = []
    update_bytes = []
    update_insert_ratio = []

    with data_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        required = {"gc_ratio", "reinsert_bytes", "update_bytes", "update_insert_ratio"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing required columns in {data_path}: {sorted(missing)}")

        for row in reader:
            gc_ratios.append(row["gc_ratio"].strip())
            reinsert_bytes.append(float(row["reinsert_bytes"]))
            update_bytes.append(float(row["update_bytes"]))
            update_insert_ratio.append(float(row["update_insert_ratio"]))

    if not gc_ratios:
        raise ValueError(f"No data rows found in {data_path}")

    return (
        gc_ratios,
        np.array(reinsert_bytes, dtype=float),
        np.array(update_bytes, dtype=float),
        np.array(update_insert_ratio, dtype=float),
    )


def style_axes(ax):
    for spine in ax.spines.values():
        spine.set_linewidth(AXIS_LINEWIDTH)
    ax.tick_params(width=TICK_LINEWIDTH)


def compute_axis_top(max_value: float, padding_ratio: float, min_extra: float) -> float:
    if max_value <= 0:
        return 1.0
    return max_value + max(max_value * padding_ratio, min_extra)


def compute_nice_axis(max_value: float, intervals: int):
    if max_value <= 0:
        return 1.0, 0.2

    raw_step = max_value / max(1, intervals)
    magnitude = 10 ** np.floor(np.log10(raw_step))
    normalized = raw_step / magnitude

    if normalized <= 1:
        nice_base = 1
    elif normalized <= 2:
        nice_base = 2
    elif normalized <= 5:
        nice_base = 5
    else:
        nice_base = 10

    step = nice_base * magnitude
    axis_top = np.ceil(max_value / step) * step
    return float(axis_top), float(step)


def build_tick_formatter(axis_top: float):
    if axis_top < 1.0:
        precision = 2
    elif axis_top < 10.0:
        precision = 1
    else:
        precision = 0

    def _formatter(value, _pos):
        text = f"{value:.{precision}f}"
        if precision > 0:
            text = text.rstrip("0").rstrip(".")
        return text

    return FuncFormatter(_formatter)


def configure_y_axis(
    ax,
    axis_top: float,
    *,
    nbins: int,
    labelpad: float,
    tick_pad: float,
) -> None:
    ax.set_ylim(0, axis_top)
    ax.yaxis.set_major_locator(
        MaxNLocator(nbins=nbins, min_n_ticks=max(4, nbins - 1), prune="upper")
    )
    ax.yaxis.set_major_formatter(build_tick_formatter(axis_top))
    ax.yaxis.labelpad = labelpad
    ax.tick_params(axis="y", which="major", pad=tick_pad, width=TICK_LINEWIDTH, length=6)


def configure_left_bar_axis(ax, max_bar_value: float) -> float:
    axis_top, tick_step = compute_nice_axis(max_bar_value, LEFT_Y_NBINS)
    ticks = np.arange(0.0, axis_top + tick_step * 0.5, tick_step)

    ax.set_ylim(0, axis_top)
    ax.set_yticks(ticks)
    ax.yaxis.set_major_formatter(build_tick_formatter(axis_top))
    ax.yaxis.labelpad = LEFT_Y_LABELPAD
    ax.tick_params(axis="y", which="major", pad=LEFT_Y_TICK_PAD, width=TICK_LINEWIDTH, length=6)
    return axis_top


def plot(gc_ratios, reinsert_bytes, update_bytes, ratio, args: argparse.Namespace) -> None:
    plt.rcParams.update(
        {
            "font.family": GLOBAL_FONT_FAMILY,
            "font.size": GLOBAL_FONT_SIZE,
        }
    )

    # Bars use GB for readability.
    reinsert_gb = reinsert_bytes / (1024.0**3)
    update_gb = update_bytes / (1024.0**3)

    x = np.arange(len(gc_ratios))
    width = 0.36

    fig, ax1 = plt.subplots(figsize=PANEL_FIGSIZE)
    max_bar_value = float(max(np.max(reinsert_gb), np.max(update_gb)))
    bar_label_offset = max(max_bar_value * BAR_LABEL_OFFSET_RATIO, MIN_BAR_LABEL_OFFSET)

    bars_reinsert = ax1.bar(
        x - width / 2,
        reinsert_gb,
        width,
        label="Reinsert",
        color=REINSERT_COLOR,
        edgecolor="black",
        linewidth=BAR_EDGE_LINEWIDTH,
    )
    bars_update = ax1.bar(
        x + width / 2,
        update_gb,
        width,
        label="Parity update",
        color=UPDATE_COLOR,
        edgecolor="black",
        linewidth=BAR_EDGE_LINEWIDTH,
    )

    ax1.set_xticks(x)
    ax1.set_xticklabels(gc_ratios)
    ax1.set_xlabel(args.x_axis_label)
    ax1.set_ylabel(args.bar_y_label)
    style_axes(ax1)
    configure_left_bar_axis(ax1, max_bar_value)

    ax2 = ax1.twinx()
    line_x = x + width / 2
    (line_ratio,) = ax2.plot(
        line_x,
        ratio,
        marker="o",
        markersize=8,
        linewidth=2.5,
        linestyle="-",
        label="Write amplification",
        color=AMPLIFICATION_COLOR,
    )
    ax2.set_ylabel(args.line_y_label)
    style_axes(ax2)
    max_ratio_value = float(np.max(ratio))
    line_label_offset = max(max_ratio_value * LINE_LABEL_OFFSET_RATIO, MIN_LINE_LABEL_OFFSET)
    right_axis_top = max(
        compute_axis_top(
            max_ratio_value + line_label_offset,
            padding_ratio=LINE_TOP_PADDING_RATIO,
            min_extra=0.12,
        ),
        (max_ratio_value + line_label_offset) / RIGHT_LINE_HEIGHT_FRACTION,
    )
    configure_y_axis(
        ax2,
        right_axis_top,
        nbins=RIGHT_Y_NBINS,
        labelpad=RIGHT_Y_LABELPAD,
        tick_pad=RIGHT_Y_TICK_PAD,
    )

    for bar in list(bars_reinsert) + list(bars_update):
        h = bar.get_height()
        ax1.text(
            bar.get_x() + bar.get_width() / 2,
            h + bar_label_offset,
            f"{int(round(h))}",
            ha="center",
            va="bottom",
            fontsize=VALUE_FONT_SIZE,
        )

    for xi, yi in zip(line_x, ratio):
        ax2.text(
            float(xi),
            yi - line_label_offset,
            f"{yi:.1f}",
            ha="center",
            va="top",
            fontsize=VALUE_FONT_SIZE,
        )

    handles1, labels1 = ax1.get_legend_handles_labels()
    handles2 = [line_ratio]
    labels2 = ["Write amplification"]
    fig.legend(
        handles1 + handles2,
        labels1 + labels2,
        loc="upper center",
        bbox_to_anchor=(0.5, 1.03),
        ncol=3,
        frameon=False,
        fontsize=GLOBAL_FONT_SIZE,
    )

    ax1.set_axisbelow(True)
    ax1.grid(axis="y", which="major", linestyle="--", alpha=0.35)
    fig.tight_layout(rect=(0.02, 0, 0.98, 0.93))
    fig.savefig(args.output)
    print(f"Saved plot to {args.output}")


def main() -> None:
    args = parse_args()
    gc_ratios, reinsert_bytes, update_bytes, ratio = read_tsv(Path(args.data))
    plot(gc_ratios, reinsert_bytes, update_bytes, ratio, args)


if __name__ == "__main__":
    main()
