import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

REINSERT_COLOR = "#9AC9DB"
UPDATE_COLOR = "#BB9727"
AMPLIFICATION_COLOR = "#C82423"

PANEL_FIGSIZE = (8, 5)
GLOBAL_FONT_FAMILY = "Arial"
GLOBAL_FONT_SIZE = 34.0
VALUE_FONT_SIZE = 24.0
AXIS_LINEWIDTH = 1.5
TICK_LINEWIDTH = 1.5
BAR_EDGE_LINEWIDTH = 1.4


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot write amplification from TSV generated by run_motivation_exp2b.sh"
    )
    parser.add_argument(
        "--data",
        default="write_amplification.tsv",
        help="Input TSV path with columns: gc_ratio, reinsert_bytes, update_bytes, update_insert_ratio",
    )
    parser.add_argument(
        "--output",
        default="write_amplification.png",
        help="Output image filename (png/pdf/svg)",
    )
    parser.add_argument(
        "--x-axis-label",
        default="GC Ratio",
        help="X-axis label",
    )
    parser.add_argument(
        "--bar-y-label",
        default="Written Data (GB)",
        help="Left y-axis label for bars",
    )
    parser.add_argument(
        "--line-y-label",
        default="Update/Reinsert",
        help="Right y-axis label for line",
    )
    return parser.parse_args()


def read_tsv(data_path: Path):
    if not data_path.exists():
        raise FileNotFoundError(f"Input file not found: {data_path}")

    gc_ratios = []
    reinsert_bytes = []
    update_bytes = []
    update_insert_ratio = []

    with data_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        required = {"gc_ratio", "reinsert_bytes", "update_bytes", "update_insert_ratio"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing required columns in {data_path}: {sorted(missing)}")

        for row in reader:
            gc_ratios.append(row["gc_ratio"].strip())
            reinsert_bytes.append(float(row["reinsert_bytes"]))
            update_bytes.append(float(row["update_bytes"]))
            update_insert_ratio.append(float(row["update_insert_ratio"]))

    if not gc_ratios:
        raise ValueError(f"No data rows found in {data_path}")

    return (
        gc_ratios,
        np.array(reinsert_bytes, dtype=float),
        np.array(update_bytes, dtype=float),
        np.array(update_insert_ratio, dtype=float),
    )


def style_axes(ax):
    for spine in ax.spines.values():
        spine.set_linewidth(AXIS_LINEWIDTH)
    ax.tick_params(width=TICK_LINEWIDTH)


def plot(gc_ratios, reinsert_bytes, update_bytes, ratio, args: argparse.Namespace) -> None:
    plt.rcParams.update(
        {
            "font.family": GLOBAL_FONT_FAMILY,
            "font.size": GLOBAL_FONT_SIZE,
        }
    )

    # Bars use GB for readability.
    reinsert_gb = reinsert_bytes / (1024.0**3)
    update_gb = update_bytes / (1024.0**3)

    x = np.arange(len(gc_ratios))
    width = 0.36

    fig, ax1 = plt.subplots(figsize=PANEL_FIGSIZE)

    bars_reinsert = ax1.bar(
        x - width / 2,
        reinsert_gb,
        width,
        label="Reinsert Data",
        color=REINSERT_COLOR,
        edgecolor="black",
        linewidth=BAR_EDGE_LINEWIDTH,
    )
    bars_update = ax1.bar(
        x + width / 2,
        update_gb,
        width,
        label="Update Data",
        color=UPDATE_COLOR,
        edgecolor="black",
        linewidth=BAR_EDGE_LINEWIDTH,
    )

    ax1.set_xticks(x)
    ax1.set_xticklabels(gc_ratios)
    ax1.set_xlabel(args.x_axis_label)
    ax1.set_ylabel(args.bar_y_label)
    ax1.set_ylim(bottom=0)
    style_axes(ax1)

    ax2 = ax1.twinx()
    (line_ratio,) = ax2.plot(
        x,
        ratio,
        marker="o",
        markersize=8,
        linewidth=2.5,
        linestyle="-",
        label="Update/Reinsert",
        color=AMPLIFICATION_COLOR,
    )
    ax2.set_ylabel(args.line_y_label)
    ax2.set_ylim(bottom=0)
    style_axes(ax2)

    for bar in list(bars_reinsert) + list(bars_update):
        h = bar.get_height()
        ax1.text(
            bar.get_x() + bar.get_width() / 2,
            h,
            f"{h:.2f}",
            ha="center",
            va="bottom",
            fontsize=VALUE_FONT_SIZE,
        )

    y_offset = 0.03 * max(1.0, float(np.max(ratio)))
    for xi, yi in zip(x, ratio):
        ax2.text(
            float(xi),
            yi + y_offset,
            f"{yi:.2f}",
            ha="center",
            va="bottom",
            fontsize=VALUE_FONT_SIZE,
            color=AMPLIFICATION_COLOR,
        )

    handles1, labels1 = ax1.get_legend_handles_labels()
    handles2 = [line_ratio]
    labels2 = ["Update/Reinsert"]
    fig.legend(
        handles1 + handles2,
        labels1 + labels2,
        loc="upper center",
        bbox_to_anchor=(0.5, 1.03),
        ncol=3,
        frameon=False,
        fontsize=GLOBAL_FONT_SIZE * 0.7,
    )

    ax1.grid(axis="y", linestyle="--", alpha=0.35)
    fig.tight_layout(rect=(0, 0, 1, 0.93))
    fig.savefig(args.output)
    print(f"Saved plot to {args.output}")


def main() -> None:
    args = parse_args()
    gc_ratios, reinsert_bytes, update_bytes, ratio = read_tsv(Path(args.data))
    plot(gc_ratios, reinsert_bytes, update_bytes, ratio, args)


if __name__ == "__main__":
    main()
